# Use the official MySQL image from Docker Hub
FROM mysql:8.0

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=jasaAdmin1873
ENV MYSQL_DATABASE=jasa
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=jasaForTheWin

# Copy initialization SQL script
COPY init.sql /docker-entrypoint-initdb.d/

# Expose port 3307
EXPOSE 3307